/**
 * 【问卷·A2】导演 / 演员备选列表
 * 当 GET /api/preferences/* 失败时，AuthView 使用此数据渲染气泡
 * 速查索引: src/code-map.js → AUTH_PAGE_MAP (A2)
 */
export const FALLBACK_DIRECTORS = [
  { name: '克里斯托弗·诺兰', count: 10 },
  { name: '史蒂文·斯皮尔伯格', count: 12 },
  { name: '马丁·斯科塞斯', count: 8 },
  { name: '张艺谋', count: 15 },
  { name: '李安', count: 6 },
  { name: '王家卫', count: 7 },
  { name: '昆汀·塔伦蒂诺', count: 9 },
  { name: '詹姆斯·卡梅隆', count: 5 },
  { name: '彼得·杰克逊', count: 6 },
  { name: '克林特·伊斯特伍德', count: 8 },
  { name: '伍迪·艾伦', count: 11 },
  { name: '宫崎骏', count: 13 },
  { name: '北野武', count: 7 },
  { name: '黑泽明', count: 5 },
  { name: '侯孝贤', count: 4 },
  { name: '贾樟柯', count: 6 },
  { name: '陈凯歌', count: 8 },
  { name: '冯小刚', count: 10 },
  { name: '姜文', count: 5 },
  { name: '宁浩', count: 6 },
  { name: '徐峥', count: 7 },
  { name: '陈思诚', count: 5 },
  { name: '吴京', count: 4 },
  { name: '周星驰', count: 9 },
  { name: '杜琪峰', count: 8 },
  { name: '刘伟强', count: 6 },
  { name: '叶伟信', count: 5 },
  { name: '麦兆辉', count: 4 },
  { name: '庄文强', count: 4 },
  { name: '林超贤', count: 5 },
]

/** 问卷演员备选（与 FALLBACK_DIRECTORS 配套） */
export const FALLBACK_ACTORS = [
  { name: '汤姆·克鲁斯', count: 15 },
  { name: '莱昂纳多·迪卡普里奥', count: 12 },
  { name: '布拉德·皮特', count: 11 },
  { name: '约翰尼·德普', count: 13 },
  { name: '罗伯特·唐尼', count: 9 },
  { name: '小罗伯特·唐尼', count: 8 },
  { name: '马特·达蒙', count: 10 },
  { name: '乔治·克鲁尼', count: 7 },
  { name: '威尔·史密斯', count: 14 },
  { name: '丹泽尔·华盛顿', count: 11 },
  { name: '摩根·弗里曼', count: 12 },
  { name: '杰克·尼科尔森', count: 8 },
  { name: '阿尔·帕西诺', count: 9 },
  { name: '达斯汀·霍夫曼', count: 7 },
  { name: '汤姆·汉克斯', count: 13 },
  { name: '周润发', count: 15 },
  { name: '刘德华', count: 18 },
  { name: '梁朝伟', count: 12 },
  { name: '张国荣', count: 10 },
  { name: '周星驰', count: 14 },
  { name: '李连杰', count: 11 },
  { name: '成龙', count: 16 },
  { name: '甄子丹', count: 10 },
  { name: '吴京', count: 8 },
  { name: '张震', count: 7 },
  { name: '黄渤', count: 12 },
  { name: '徐峥', count: 9 },
  { name: '沈腾', count: 8 },
  { name: '王宝强', count: 10 },
  { name: '刘昊然', count: 6 },
]
