/**
 * =============================================================================
 * 代码速查索引（登录注册·问卷 + 首页 + 电影详情页）
 * =============================================================================
 * 用法：Ctrl+F 搜索界面功能名（如「播放预告片」「收藏」「问卷」）
 * 然后按 frontend → searchInFile → api → backend → service 顺序定位代码
 * =============================================================================
 */

/** @type {Array<{id:string, ui:string, frontend:string, searchInFile:string, api:string, backend:string, service:string}>} */
export const HOME_PAGE_MAP = [
  {
    id: 'H1',
    ui: '首页 · 整体入口',
    frontend: 'views/HomeView.vue',
    searchInFile: 'ROW_SECTIONS',
    api: 'movieApi.home',
    backend: 'GET /api/movies/home',
    service: 'movie_service.get_home_sections',
  },
  {
    id: 'H1b',
    ui: '首页 · 问卷偏好推荐',
    frontend: 'views/HomeView.vue',
    searchInFile: 'loadPreferenceMovies',
    api: 'recommendApi.byPreference',
    backend: 'POST /api/recommend/preference',
    service: 'recommendation_service.get_preference_recommendations',
  },
  {
    id: 'H2',
    ui: '首页 · 顶部大轮播 Hero',
    frontend: 'components/HeroCarousel.vue',
    searchInFile: 'loadTrailer',
    api: 'movieApi.trailer',
    backend: 'GET /api/movies/<id>/trailer',
    service: 'trailer_service.resolve_trailer',
  },
  {
    id: 'H2b',
    ui: '首页 · 轮播预告播放',
    frontend: 'components/MediaPlayer.vue',
    searchInFile: 'resolveMediaUrl',
    api: 'GET /api/trailers/<id>',
    backend: 'GET /api/trailers/<movie_id>',
    service: 'trailer_service.get_local_trailer_path',
  },
  {
    id: 'H3',
    ui: '首页 · 热门/高分/新上映',
    frontend: 'views/HomeView.vue → MovieRow.vue → MovieCard.vue',
    searchInFile: 'ROW_SECTIONS',
    api: 'movieApi.home',
    backend: 'GET /api/movies/home',
    service: 'movie_service.get_home_sections',
  },
  {
    id: 'H4',
    ui: '首页 · 底部短评展示',
    frontend: 'components/HomeCommentShowcase.vue',
    searchInFile: 'homeComments',
    api: 'movieApi.homeComments',
    backend: 'GET /api/movies/home/comments',
    service: 'comment_service.get_home_section_comments',
  },
]

/** @type {typeof HOME_PAGE_MAP} */
export const AUTH_PAGE_MAP = [
  {
    id: 'A1',
    ui: '登录注册 · 入口页',
    frontend: 'views/AuthView.vue',
    searchInFile: 'handleLogin',
    api: 'authApi.login / authApi.register',
    backend: 'POST /api/auth/login, POST /api/auth/register',
    service: 'models.User',
  },
  {
    id: 'A2',
    ui: '注册后 · 偏好问卷（类型/导演/演员）',
    frontend: 'views/AuthView.vue',
    searchInFile: 'handleSave',
    api: 'preferenceApi.directors / preferenceApi.actors',
    backend: 'GET /api/preferences/directors, GET /api/preferences/actors',
    service: 'movie_service.get_mysql',
  },
  {
    id: 'A4',
    ui: '问卷 · 视频背景',
    frontend: 'components/PreferenceVideoBg.vue',
    searchInFile: 'processFrame',
    api: '—',
    backend: '—',
    service: '—',
  },
  {
    id: 'A5',
    ui: '登录态 / 问卷偏好存储',
    frontend: 'stores/user.js',
    searchInFile: 'savePreference',
    api: 'authApi.* / localStorage userPreference',
    backend: 'POST /api/auth/*, GET /api/auth/me',
    service: 'models.User',
  },
  {
    id: 'A3',
    ui: '登录态 · 路由守卫',
    frontend: 'router/index.js',
    searchInFile: 'beforeEach',
    api: 'authApi.me',
    backend: 'GET /api/auth/me',
    service: '—',
  },
]

/** @type {typeof HOME_PAGE_MAP} */
export const DETAIL_PAGE_MAP = [
  {
    id: 'D0',
    ui: '详情页 · 入口与加载',
    frontend: 'views/MovieDetailView.vue',
    searchInFile: 'useMovieDetailPage',
    api: 'movieApi.detail',
    backend: 'GET /api/movies/<id>',
    service: 'movie_service.get_movie_by_id',
  },
  {
    id: 'D0b',
    ui: '详情页 · 全部逻辑',
    frontend: 'composables/detail/useMovieDetailPage.js',
    searchInFile: 'async function load',
    api: '（见各函数注释）',
    backend: 'backend/app.py',
    service: 'services/*.py',
  },
  {
    id: 'D1',
    ui: '详情页 · Hero 信息区',
    frontend: 'components/detail-page/01-DetailHeroSection.vue',
    searchInFile: 'detail-hero__title',
    api: 'movieApi.detail',
    backend: 'GET /api/movies/<id>',
    service: 'movie_service.get_movie_by_id',
  },
  {
    id: 'D1a',
    ui: '详情页 · 按钮「添加到片单」',
    frontend: '01-DetailHeroSection.vue',
    searchInFile: 'toggleList',
    api: 'listApi.add/remove',
    backend: 'POST/DELETE /api/lists',
    service: 'app.py user_lists',
  },
  {
    id: 'D1b',
    ui: '详情页 · 按钮「标记为收藏」',
    frontend: '01-DetailHeroSection.vue',
    searchInFile: 'toggleFavorite',
    api: 'favoriteApi.add/remove',
    backend: 'POST/DELETE /api/favorites',
    service: 'app.py favorites',
  },
  {
    id: 'D1c',
    ui: '详情页 · 按钮「添加到待看片单」',
    frontend: '01-DetailHeroSection.vue',
    searchInFile: 'toggleWatchlist',
    api: 'watchlistApi.add/remove',
    backend: 'POST/DELETE /api/watchlist',
    service: 'app.py watchlist',
  },
  {
    id: 'D1d',
    ui: '详情页 · 按钮「播放正片」',
    frontend: '01-DetailHeroSection.vue',
    searchInFile: 'switchToMovieTab',
    api: 'movieApi.play',
    backend: 'GET /api/movies/<id>/play',
    service: 'video_service.resolve_playback',
  },
  {
    id: 'D1e',
    ui: '详情页 · 按钮「播放预告片」',
    frontend: '01-DetailHeroSection.vue',
    searchInFile: 'playTrailer',
    api: 'movieApi.trailer',
    backend: 'GET /api/movies/<id>/trailer',
    service: 'trailer_service.resolve_trailer',
  },
  {
    id: 'D1f',
    ui: '详情页 · 提交评分 / 删除评分',
    frontend: '01-DetailHeroSection.vue',
    searchInFile: 'submitRating',
    api: 'ratingApi.rate/remove',
    backend: 'POST/DELETE /api/ratings',
    service: 'app.py rate_movie',
  },
  {
    id: 'D2',
    ui: '详情页 · 播放器区',
    frontend: 'components/detail-page/02-DetailPlayerSection.vue',
    searchInFile: 'movie-player',
    api: 'movieApi.play / movieApi.trailer',
    backend: '/play 或 /trailer',
    service: 'video_service / trailer_service',
  },
  {
    id: 'D2a',
    ui: '详情页 · 平台观看按钮',
    frontend: '02-DetailPlayerSection.vue',
    searchInFile: 'openWatchPage',
    api: 'movieApi.watchLinks',
    backend: 'GET /api/movies/<id>/watch-links',
    service: 'streaming_service.resolve_watch_links',
  },
  {
    id: 'D2b',
    ui: '详情页 · 重新加载',
    frontend: '02-DetailPlayerSection.vue',
    searchInFile: 'loadTrailer(true)',
    api: 'play 或 trailer',
    backend: '/play 或 /trailer',
    service: 'video_service / trailer_service',
  },
  {
    id: 'D3',
    ui: '详情页 · 短评发表/删除',
    frontend: 'components/detail-page/03-DetailReviewsSection.vue',
    searchInFile: 'submitComment',
    api: 'commentApi.submit/remove',
    backend: 'POST/DELETE /api/comments',
    service: 'app.py comments',
  },
  {
    id: 'D3b',
    ui: '详情页 · 评论翻译',
    frontend: '03-DetailReviewsSection.vue',
    searchInFile: 'toggleReviewTranslation',
    api: 'translateApi.translate',
    backend: 'POST /api/translate',
    service: 'translate_service.translate_text',
  },
  {
    id: 'D4',
    ui: '详情页 · 相似推荐',
    frontend: 'components/detail-page/04-DetailSimilarSection.vue',
    searchInFile: '同类相似推荐',
    api: 'recommendApi.similar',
    backend: 'GET /api/recommend/similar/<id>',
    service: 'recommendation_service.get_content_similar_movies',
  },
]

/** @type {typeof HOME_PAGE_MAP} */
export const SHARED_MAP = [
  {
    id: 'S1',
    ui: '前后端连接 · axios 配置',
    frontend: 'api/index.js',
    searchInFile: 'baseURL',
    api: "baseURL: '/api'",
    backend: 'backend/app.py',
    service: '—',
  },
  {
    id: 'S2',
    ui: '路由 · 登录/首页/详情',
    frontend: 'router/index.js',
    searchInFile: 'auth / home / movie-detail',
    api: '—',
    backend: '—',
    service: '—',
  },
  {
    id: 'S3',
    ui: '预告缓存（首页+详情共用）',
    frontend: 'utils/trailerCache.js',
    searchInFile: 'prefetchTrailer',
    api: 'movieApi.trailer',
    backend: '/trailer + /trailers/local-ids',
    service: 'trailer_service',
  },
]

export const ALL_CODE_MAP = [...AUTH_PAGE_MAP, ...HOME_PAGE_MAP, ...DETAIL_PAGE_MAP, ...SHARED_MAP]
